<style type="text/css">
	#fastnav{ position: absolute; top: 40px; left: 430px; }
	#fastnav a { margin-right: 6px; padding: 4px 6px; border: 1px solid #a5181a; text-decoration: none; }
	#fastnav a:hover{ background: #4c1111; }
</style>

<div id="fastnav">
  <a href="http://123.123.123.123:7790/ServerAdmin/current/info">KF1</a>
  <a href="http://123.123.123.123:7791/ServerAdmin/current/info">KF2</a>
  <a href="http://123.123.123.123:7792/ServerAdmin/current/info">KF3</a>
  <a href="http://123.123.123.123:7793/ServerAdmin/current/info">KF4</a>
</div>
