<!-- #include file="header_base.inc" -->

<div id="header">
  <!-- #include file="header_fastnav.inc" -->
  <h1><span>Killing Floor 2 WebAdmin</span></h1>
  <h3 id="pageUri"><%page.uri%></h3>
  <h4 id="adminName">Welcome <span class="username"><%admin.name%></span></h4>
  <div id="pageInfo">
    <h2 id="pageTitle"><%page.title%></h2>
    <p id="pageDescription"><%page.description%></p>
  </div>
</div>

<div id="gamesummary">
<%gamesummary%>
</div>

<div id="messages">
<%messages%>
</div>
